feat(executor): added MsgUpsertSequencer consensus message
dymensionxyz/dymint pull request #1120
Opened 2024-10-04 17:43 UTC by keruch

# PR Standards

ADR link https://www.notion.so/dymension/ADR-x-Sequencer-Reward-Address-On-Rollapp-da84af6888c141d0a4c1a8df256a5025
Closes https://github.com/dymensionxyz/dymension/issues/1248

---

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

2024-10-09 10:57 UTC, jgimeno commented on block/produce.go
> +	block = m.Executor.CreateBlock(newHeight, lastCommit, lastHeaderHash, proposerHashForBlock, m.State, maxBlockDataSize, consensusMsgs...)
Ideally there should be only one point of adding consensus messages. Given they come from the ConsensusMessagesStream this should send them there.

The only problem I see here is that there is no implementation of the stream as of now. I would put a message somewhere with a TODO to unify it.

2024-10-12 15:02 UTC, omritoptix approved these changes
looks good. small code cleanliness comments.

2024-10-12 15:08 UTC, omritoptix requested changes
I notice now we introduce a circular dependency with the RDK which makes this pr fails to build also.

I think we should avoid the circular depedency, it makes it really difiicult to maintain after. 

can't we just copy the protos?

2024-10-15 09:28 UTC, mtsitrin requested changes

2024-10-15 09:28 UTC, mtsitrin commented on p2p/client_test.go
> +// TestBootstrapping TODO: this test is flaky in main. Try running it 100 times to reproduce.
add reference to https://github.com/dymensionxyz/dymint/issues/869

2024-10-15 09:28 UTC, mtsitrin commented on block/produce.go
> +type nextProposerInfo struct {
this `nextProposerInfo struct` is uneeded, and changes alot of APIs just to be used in `consensusMsgsOnCreateBlock`.
`nextProposerAddr` can be queried using `m.State.Sequencers.GetByHash` (similar to `SetByHash`)

2024-10-15 09:28 UTC, mtsitrin commented on block/produce.go
> +func (m *Manager) consensusMsgsOnCreateBlock(
i suggest to move to separate file, to have all consesnsMsg related logic

2024-10-15 09:28 UTC, mtsitrin commented on block/produce.go
> +	sequencertypes "github.com/dymensionxyz/dymint/types/pb/rollapp/sequencers/types"
```suggestion
	rdktypes "github.com/dymensionxyz/dymint/types/pb/rollapp/sequencers/types"
```

2024-10-15 09:28 UTC, mtsitrin commented on block/produce.go
> +		Operator:   nextProposerSettlementAddr,
we're passing "dym1...." to the RDK, which needs to be converted to the rollapp's native prefix.
Maybe we should pass the []byte of the address, not the bech32 representation

2024-10-18 09:14 UTC, closed without merging