fix: set const ReadHeaderTimeout to dymint RPC server
dymensionxyz/dymint pull request #671
Opened 2024-04-15 06:55 UTC by mtsitrin

* setting client timeout to mitigate HTTP based DoS attacks

Close #652 

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

2024-04-15 13:43 UTC, danwt requested changes

2024-04-15 13:43 UTC, danwt commented on rpc/server.go
> +	}
can we also have readtimeout

And use timeouthandler to wrap the handler?

2024-04-16 11:24 UTC, mtsitrin commented
I've added `ReadHeaderTimeout` to mitigate network based slow attack (which can happen before the execution of `timeouthandler`)

2024-04-16 11:29 UTC, danwt commented
refactor :green_apple: 
timeout: we still want https://pkg.go.dev/net/http#TimeoutHandler and  server.ReadTimeout right?

	// ReadTimeout is the maximum duration for reading the entire
	// request, including the body. A zero or negative value means
	// there will be no timeout.
	//
	// Because ReadTimeout does not let Handlers make per-request
	// decisions on each request body's acceptable deadline or
	// upload rate, most users will prefer to use
	// ReadHeaderTimeout. It is valid to use them both.
	ReadTimeout time.Duration
?

2024-04-16 11:34 UTC, danwt approved these changes

2024-04-16 12:23 UTC, mtsitrin commented
AFAICT, we want server with `ReadHeaderTimeout` defined and `http.TimeoutHandler` as the handler.

2024-04-16 13:02 UTC, zale144 approved these changes

2024-04-16 13:09 UTC, zale144 commented
@danwt I think this is about the timeout for reading headers, to prevent someone from sending a ridiculously large header that would take forever to read. But I am not sure if `http.TimeoutHandler` would cover that.

2024-04-17 08:08 UTC, merged